vich_uploader:
    db_driver: orm

    mappings:
        trainer_image:
            uri_prefix: /assets/img/trainers
            upload_destination: '%kernel.project_dir%/public/assets/img/trainers'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
